import { InterviewQuestion } from './interviewPrepData';

export const CSHARP_PART3: InterviewQuestion[] = [
  {
    id: 'csnet-36',
    category: 'C# & .NET',
    question: '36. How does Output Caching in .NET 7/8 differ from legacy Response Caching, and how do Cache Eviction Tags work?',
    difficulty: 'Senior (6+ YOE)',
    tags: ['C#', 'Output Caching', 'Response Caching', 'ASP.NET Core', 'Performance'],
    shortSummary: 'Covers server-side output caching, Redis backing stores, tag-based invalidation, and VaryByHeader.',
    detailedAnswer: {
      executiveSummary: 'Legacy `ResponseCaching` relies on HTTP client `Cache-Control` headers and clients can bypass the cache. `OutputCaching` (introduced in .NET 7) is a full server-side caching engine that guarantees cache hits regardless of client request headers. It supports Redis distributed backends, streaming responses, locking against cache stampedes, and tag-based invalidation via `IOutputCacheStore.EvictByTagAsync()`.',
      keyPoints: [
        'Guaranteed Server-Side Cache: Server controls caching policy without relying on client headers.',
        'Tag-Based Invalidation: Group cached endpoints under tags (e.g. "mortgage-rates") and evict all matching entries simultaneously.',
        'Locking Protection: Built-in mutex locks prevent stampedes when an entry expires.',
        'Distributed Store: Back output cache with Redis using `AddStackExchangeRedisOutputCache`.'
      ],
      codeOrQuerySnippet: {
        title: 'Output Caching with Tag Invalidation in ASP.NET Core',
        language: 'csharp',
        code: `// Program.cs
builder.Services.AddOutputCache(options =>
{
    options.AddBasePolicy(builder => builder.Expire(TimeSpan.FromMinutes(10)));
    options.AddPolicy("RatesPolicy", builder => builder
        .Expire(TimeSpan.FromHours(1))
        .Tag("rates-tag")
        .SetVaryByQuery("stateCode"));
});

// Endpoint registration:
app.MapGet("/api/rates/{stateCode}", (string stateCode, IRateService svc) => 
    svc.GetRatesAsync(stateCode))
    .CacheOutput("RatesPolicy");

// Invalidate on update:
app.MapPost("/api/rates/update", async (IOutputCacheStore cacheStore) =>
{
    await cacheStore.EvictByTagAsync("rates-tag", default);
    return Results.Ok("Cache invalidated");
});`
      },
      proTipOrPitfall: 'By default, Output Caching does NOT cache authenticated requests. If you want to cache responses for authenticated users, you must explicitly enable `.SetVaryByHeader("Authorization")` in your custom policy.',
      studyResources: [
        {
          title: 'Output caching middleware in ASP.NET Core',
          url: 'https://learn.microsoft.com/en-us/aspnet/core/performance/caching/output',
          source: 'Microsoft Learn'
        }
      ]
    }
  },
  {
    id: 'csnet-37',
    category: 'C# & .NET',
    question: '37. How does the ASP.NET Core Data Protection API work, and how do you configure it in multi-instance cloud deployments?',
    difficulty: 'Staff / Lead Architect',
    tags: ['C#', 'Data Protection', 'Security', 'Azure Key Vault', 'Cryptography', 'Cloud'],
    shortSummary: 'Explains cryptographic key rings, key rotation, Azure Blob Storage key persistence, and Azure Key Vault key encryption.',
    detailedAnswer: {
      executiveSummary: 'The ASP.NET Core Data Protection API (`IDataProtectionProvider`) generates and manages cryptographic keys for securing cookies, anti-forgery tokens, and state tokens. In a load-balanced multi-pod environment, if each instance uses local ephemeral keys, a token generated by Pod A cannot be decrypted by Pod B. In production, keys must be persisted to shared storage (Azure Blob Storage / AWS S3) and encrypted at rest with a master key in Azure Key Vault or AWS KMS.',
      keyPoints: [
        'Cryptographic Key Ring: Manages symmetric encryption keys (AES-256-GCM) with automatic 90-day rotation.',
        'Cluster Synchronization: All pods must share the same key storage repository to decrypt cookies and CSRF tokens.',
        'Key Encryption at Rest: Master key in Azure Key Vault encrypts the key ring before writing to storage.',
        'Purpose Strings: Unique purpose strings isolate cryptographic tokens across features.'
      ],
      codeOrQuerySnippet: {
        title: 'Configuring Data Protection for Azure Cloud Clusters',
        language: 'csharp',
        code: `builder.Services.AddDataProtection()
    .SetApplicationName("EnterpriseMortgageApp")
    .PersistKeysToAzureBlobStorage(new Uri("https://myaccount.blob.core.windows.net/keys/dataprotection.xml"), new DefaultAzureCredential())
    .ProtectKeysWithAzureKeyVault(new Uri("https://myvault.vault.azure.net/keys/dp-master-key"), new DefaultAzureCredential());`
      },
      proTipOrPitfall: 'Always set a consistent `SetApplicationName(...)` across all microservices sharing data protection tokens; otherwise, the runtime isolates key rings by app domain path.',
      studyResources: [
        {
          title: 'ASP.NET Core Data Protection Overview',
          url: 'https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/introduction',
          source: 'Microsoft Learn'
        }
      ]
    }
  },
  {
    id: 'csnet-38',
    category: 'C# & .NET',
    question: '38. How do JWT Authentication, Token Validation Parameters, and Custom Authorization Policies with IAuthorizationHandler secure ASP.NET Core APIs?',
    difficulty: 'Senior (6+ YOE)',
    tags: ['C#', 'JWT', 'Security', 'OAuth2', 'Authorization', 'Entra ID'],
    shortSummary: 'Explains signing key validation, issuer/audience validation, clock skew, and custom requirement handlers.',
    detailedAnswer: {
      executiveSummary: 'ASP.NET Core validates JWT Bearer tokens using `JwtBearerHandler` configured with `TokenValidationParameters` (validating signature, issuer, audience, and expiration). Beyond basic role checks, complex business authorization uses Policy-Based Authorization (`IAuthorizationRequirement` and `AuthorizationHandler<T>`), evaluating contextual user claims, tenant memberships, and domain constraints.',
      keyPoints: [
        'TokenValidationParameters: Validate `ValidateIssuerSigningKey`, `ValidIssuer`, `ValidAudience`, and `ValidateLifetime`.',
        'ClockSkew: Runtime defaults to 5 minutes clock skew tolerance; reduce to `TimeSpan.Zero` for strict token expiry enforcement.',
        'Custom Authorization: Implement `AuthorizationHandler<MinimumCreditScoreRequirement>` for fine-grained rules.',
        'ClaimsTransformation: Implement `IClaimsTransformation` to augment incoming JWT claims from database at runtime.'
      ],
      codeOrQuerySnippet: {
        title: 'Custom Policy Authorization Handler in ASP.NET Core',
        language: 'csharp',
        code: `public record MinimumLoanAuthorityRequirement(decimal MaxApprovalLimit) : IAuthorizationRequirement;

public class LoanAuthorityHandler : AuthorizationHandler<MinimumLoanAuthorityRequirement>
{
    protected override Task HandleRequirementAsync(
        AuthorizationHandlerContext context, MinimumLoanAuthorityRequirement requirement)
    {
        var limitClaim = context.User.FindFirst("loan_approval_limit")?.Value;
        if (decimal.TryParse(limitClaim, out decimal userLimit) && userLimit >= requirement.MaxApprovalLimit)
        {
            context.Succeed(requirement);
        }
        return Task.CompletedTask;
    }
}

// Registration in Program.cs:
builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("CanApproveJumboLoans", policy =>
        policy.Requirements.Add(new MinimumLoanAuthorityRequirement(1_000_000m)));
});`
      },
      proTipOrPitfall: 'Never decode JWT tokens manually with `JwtSecurityTokenHandler.ReadJwtToken()` to check user claims without performing signature and lifetime validation first.',
      studyResources: [
        {
          title: 'Policy-based authorization in ASP.NET Core',
          url: 'https://learn.microsoft.com/en-us/aspnet/core/security/authorization/policies',
          source: 'Microsoft Learn'
        }
      ]
    }
  },
  {
    id: 'csnet-39',
    category: 'C# & .NET',
    question: '39. How do Anti-CSRF tokens, SameSite cookies, and CORS policies protect ASP.NET Core web applications against cross-origin attacks?',
    difficulty: 'Senior (6+ YOE)',
    tags: ['C#', 'Security', 'CSRF', 'SameSite', 'CORS', 'Web Security'],
    shortSummary: 'Explains double-submit cookie pattern, IAntiforgery service, SameSite=Strict/Lax, and CORS preflight handling.',
    detailedAnswer: {
      executiveSummary: 'Cross-Site Request Forgery (CSRF) tricks authenticated browsers into submitting unauthorized commands. ASP.NET Core mitigates this via the Antiforgery token system (double-submit cookie pattern) and modern `SameSite=Lax/Strict` cookie policies. Cross-Origin Resource Sharing (CORS) enforces browser boundaries for AJAX/Fetch requests by handling HTTP OPTIONS preflight handshakes and validating allowed origins, headers, and methods.',
      keyPoints: [
        'Antiforgery Middleware: `IAntiforgery.GetAndStoreTokens(context)` generates request & cookie token pairs.',
        'SameSite=Lax/Strict: Modern browsers suppress cookies on cross-origin POST requests.',
        'CORS Preflight: Browsers send HTTP OPTIONS before complex requests; middleware validates `Access-Control-Allow-Origin`.',
        'AutoValidateAntiforgeryToken: Automatically validates all unsafe HTTP methods (POST, PUT, DELETE).'
      ],
      codeOrQuerySnippet: {
        title: 'Hardened CORS and Antiforgery Configuration',
        language: 'csharp',
        code: `// Program.cs
builder.Services.AddCors(options =>
{
    options.AddPolicy("StrictEnterprisePolicy", policy =>
        policy.WithOrigins("https://mortgage.enterprise.com")
              .WithMethods("GET", "POST", "PUT", "DELETE")
              .WithHeaders("Content-Type", "Authorization", "X-XSRF-TOKEN")
              .AllowCredentials());
});

builder.Services.AddAntiforgery(options =>
{
    options.HeaderName = "X-XSRF-TOKEN";
    options.Cookie.SameSite = SameSiteMode.Strict;
    options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
});`
      },
      proTipOrPitfall: 'Never configure `AllowAnyOrigin()` together with `AllowCredentials()`; browsers will reject responses that permit credentials from wildcard origins.',
      studyResources: [
        {
          title: 'Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core',
          url: 'https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery',
          source: 'Microsoft Learn'
        }
      ]
    }
  },
  {
    id: 'csnet-40',
    category: 'C# & .NET',
    question: '40. How do MediatR Pipeline Behaviors implement Cross-Cutting Concerns (Validation, Logging, Performance Timing, Transactions) in CQRS architectures?',
    difficulty: 'Senior (6+ YOE)',
    tags: ['C#', 'MediatR', 'CQRS', 'Pipeline Behaviors', 'Clean Architecture'],
    shortSummary: 'Explains IPipelineBehavior<TRequest, TResponse>, fluent validation middleware, performance tracking, and transaction management.',
    detailedAnswer: {
      executiveSummary: 'In CQRS architectures using MediatR, `IPipelineBehavior<TRequest, TResponse>` wraps command and query handlers in a middleware-style pipeline. Behaviors execute sequentially around handlers, allowing cross-cutting concerns—such as FluentValidation request validation, execution timing, structured logging, and database transaction commits—to be implemented once centrally without polluting domain handlers.',
      keyPoints: [
        'Generic Pipeline: `IPipelineBehavior<TRequest, TResponse>` intercepts all requests sent through `IMediator.Send()`.',
        'Validation Behavior: Automatically executes all registered `IValidator<T>` instances and throws validation exceptions before the handler runs.',
        'Performance Behavior: Logs warnings when query execution time exceeds performance SLA (e.g. >500ms).',
        'Order of Execution: Behaviors execute in the order they are registered in the DI container.'
      ],
      codeOrQuerySnippet: {
        title: 'MediatR Validation Pipeline Behavior with FluentValidation',
        language: 'csharp',
        code: `public class ValidationBehavior<TRequest, TResponse>(
    IEnumerable<IValidator<TRequest>> validators) : IPipelineBehavior<TRequest, TResponse>
    where TRequest : notnull
{
    public async Task<TResponse> Handle(
        TRequest request, RequestHandlerDelegate<TResponse> next, CancellationToken cancellationToken)
    {
        if (!validators.Any()) return await next();

        var context = new ValidationContext<TRequest>(request);
        var validationResults = await Task.WhenAll(
            validators.Select(v => v.ValidateAsync(context, cancellationToken)));

        var failures = validationResults
            .SelectMany(r => r.Errors)
            .Where(f => f != null)
            .ToList();

        if (failures.Count != 0) throw new ValidationException(failures);

        return await next();
    }
}`
      },
      proTipOrPitfall: 'Keep pipeline behaviors stateless. Never store request-specific state in instance fields of a behavior class.',
      studyResources: [
        {
          title: 'MediatR Behaviors Documentation',
          url: 'https://github.com/jbogard/MediatR/wiki/Behaviors',
          source: 'GitHub / MediatR'
        }
      ]
    }
  },
  {
    id: 'csnet-41',
    category: 'C# & .NET',
    question: '41. How does the MassTransit Outbox Pattern ensure atomic transactional message publishing and prevent duplicate messages in distributed .NET microservices?',
    difficulty: 'Staff / Lead Architect',
    tags: ['C#', 'MassTransit', 'Transactional Outbox', 'Event-Driven', 'RabbitMQ', 'Azure Service Bus'],
    shortSummary: 'Explains dual-write problem, EF Core outbox table, background message dispatcher, and at-least-once delivery.',
    detailedAnswer: {
      executiveSummary: 'In distributed systems, writing to a database and publishing to a message broker (RabbitMQ/Azure Service Bus) within the same business transaction suffers from the "Dual-Write Problem". If the database commit succeeds but the message broker crashes (or vice versa), the system becomes inconsistent. The MassTransit Transactional Outbox writes the message directly into an Outbox database table inside the SAME local SQL transaction as the business entity. A background daemon polls and dispatches messages to the broker reliably.',
      keyPoints: [
        'Dual-Write Elimination: Database changes and outbound event records commit atomically in a single SQL transaction.',
        'Background Dispatcher: MassTransit background worker reads pending outbox messages and publishes them to the broker.',
        'Idempotent Consumer: Consuming services store processed message IDs in an Inbox table to discard duplicate deliveries.',
        'EF Core Integration: `services.AddMassTransit(x => x.AddEntityFrameworkOutbox<MortgageDbContext>());`.'
      ],
      codeOrQuerySnippet: {
        title: 'Configuring MassTransit Transactional Outbox with EF Core',
        language: 'csharp',
        code: `builder.Services.AddMassTransit(x =>
{
    x.AddEntityFrameworkOutbox<MortgageDbContext>(o =>
    {
        o.UseSqlServer();
        o.UseBusOutbox(); // Integrates outbox directly with IPublishEndpoint
        o.DuplicateDetectionWindow = TimeSpan.FromMinutes(30);
    });

    x.UsingAzureServiceBus((context, cfg) =>
    {
        cfg.Host(builder.Configuration.GetConnectionString("AzureServiceBus"));
        cfg.ConfigureEndpoints(context);
    });
});

// Inside Application Handler:
public class ApproveLoanCommandHandler(MortgageDbContext dbContext, IPublishEndpoint publishEndpoint)
{
    public async Task Handle(ApproveLoanCommand cmd, CancellationToken ct)
    {
        var loan = await dbContext.Loans.FindAsync([cmd.LoanId], ct);
        loan.Approve();

        // Saved to EF Outbox table atomically during SaveChangesAsync!
        await publishEndpoint.Publish(new LoanApprovedIntegrationEvent(loan.Id, loan.Principal), ct);
        await dbContext.SaveChangesAsync(ct);
    }
}`
      },
      proTipOrPitfall: 'Always ensure `IPublishEndpoint` is called BEFORE `dbContext.SaveChangesAsync()`. If called afterwards, the outbox message will not be included in the local transaction.',
      studyResources: [
        {
          title: 'Transactional Outbox in MassTransit',
          url: 'https://masstransit.io/documentation/patterns/transactional-outbox',
          source: 'MassTransit Docs'
        }
      ]
    }
  },
  {
    id: 'csnet-42',
    category: 'C# & .NET',
    question: '42. How does gRPC in .NET compare to REST APIs in microservice architectures, and how does HTTP/2 multiplexing reduce latency?',
    difficulty: 'Senior (6+ YOE)',
    tags: ['C#', 'gRPC', 'Protobuf', 'HTTP/2', 'Microservices', 'High Performance'],
    shortSummary: 'Compares binary Protocol Buffers vs JSON, bidirectional streaming, contract-first design, and gRPC-JSON transcoding.',
    detailedAnswer: {
      executiveSummary: 'gRPC uses binary Protocol Buffers (Protobuf) over HTTP/2, delivering up to 7-10x higher throughput and 60-80% lower CPU utilization compared to JSON REST over HTTP/1.1. HTTP/2 multiplexing allows hundreds of concurrent RPC calls over a single persistent TCP connection, eliminating head-of-line blocking. gRPC is ideal for high-throughput internal microservice-to-microservice communication, while REST/OpenAPI remains preferred for public web/mobile clients.',
      keyPoints: [
        'Binary Protobuf Serialization: Strongly typed schema (.proto files) compiled to C# classes with compact binary payloads.',
        'HTTP/2 Multiplexing: Multiple bidirectional streams execute simultaneously on a single TCP socket.',
        'Streaming Types: Supports Unary, Server Streaming, Client Streaming, and Bidirectional Streaming.',
        'gRPC-JSON Transcoding (.NET 7+): Exposes gRPC services as RESTful JSON APIs for browser clients simultaneously.'
      ],
      codeOrQuerySnippet: {
        title: 'gRPC Service Implementation in .NET 8 C#',
        language: 'csharp',
        code: `// loan_service.proto:
// service LoanService { rpc CalculateRate (RateRequest) returns (RateReply); }

public class LoanGrpcService : LoanService.LoanServiceBase
{
    private readonly IRateCalculationEngine _engine;

    public LoanGrpcService(IRateCalculationEngine engine) => _engine = engine;

    public override async Task<RateReply> CalculateRate(RateRequest request, ServerCallContext context)
    {
        var rate = await _engine.ComputeAsync(request.StateCode, (decimal)request.CreditScore);
        
        return new RateReply
        {
            CalculatedRate = (double)rate,
            Approved = rate < 7.5m
        };
    }
}`
      },
      proTipOrPitfall: 'Standard web browsers cannot initiate raw gRPC calls directly due to lack of low-level HTTP/2 framing control. Use gRPC-Web or gRPC-JSON transcoding for browser client access.',
      studyResources: [
        {
          title: 'gRPC services with C#',
          url: 'https://learn.microsoft.com/en-us/aspnet/core/grpc/',
          source: 'Microsoft Learn'
        }
      ]
    }
  },
  {
    id: 'csnet-43',
    category: 'C# & .NET',
    question: '43. How do you tune Kestrel Web Server for extreme enterprise throughput, HTTP/3 QUIC, and connection limits in .NET?',
    difficulty: 'Principal Architect',
    tags: ['C#', 'Kestrel', 'HTTP/3', 'QUIC', 'Performance', 'Networking'],
    shortSummary: 'Covers MaxConcurrentConnections, MinResponseDataRate, Socket transport, Libuv replacement, and HTTP/3 over UDP.',
    detailedAnswer: {
      executiveSummary: 'Kestrel is the cross-platform, asynchronous I/O web server powering ASP.NET Core, built on the managed Sockets transport. For high-density microservices, Kestrel settings—such as `MaxConcurrentConnections`, `MaxConcurrentUpgradedConnections`, `MinResponseDataRate` (mitigating Slowloris attacks), and HTTP/3 QUIC over UDP—can be tuned to handle tens of thousands of requests per second per node.',
      keyPoints: [
        'HTTP/3 (QUIC): Operates over UDP, eliminating TCP head-of-line blocking and enabling zero-RTT connection resumption.',
        'Slowloris Mitigation: `Limits.MinRequestBodyDataRate` disconnects malicious clients that stream data byte-by-byte.',
        'Connection Limits: Configure `Limits.MaxConcurrentConnections` and `Limits.MaxRequestBodySize` to prevent resource starvation.',
        'Socket Transport: Thread-per-core socket engine maximizes CPU cache locality and throughput.'
      ],
      codeOrQuerySnippet: {
        title: 'Hardened Kestrel Configuration with HTTP/3 Support',
        language: 'csharp',
        code: `builder.WebHost.ConfigureKestrel(options =>
{
    // Enable HTTP/1, HTTP/2, and HTTP/3 simultaneously
    options.ListenAnyIP(5001, listenOptions =>
    {
        listenOptions.Protocols = HttpProtocols.Http1AndHttp2AndHttp3;
        listenOptions.UseHttps();
    });

    options.Limits.MaxConcurrentConnections = 10_000;
    options.Limits.MaxRequestBodySize = 10 * 1024 * 1024; // 10 MB limit
    options.Limits.MinRequestBodyDataRate = new MinDataRate(bytesPerSecond: 240, gracePeriod: TimeSpan.FromSeconds(5));
    options.Limits.MinResponseDataRate = new MinDataRate(bytesPerSecond: 240, gracePeriod: TimeSpan.FromSeconds(5));
});`
      },
      proTipOrPitfall: 'HTTP/3 requires TLS 1.3 and an open UDP port on your firewall/load balancer. If UDP traffic is blocked by enterprise networks, clients will negotiate fallback to HTTP/2 over TCP.',
      studyResources: [
        {
          title: 'Configure endpoints for the ASP.NET Core Kestrel web server',
          url: 'https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints',
          source: 'Microsoft Learn'
        }
      ]
    }
  },
  {
    id: 'csnet-44',
    category: 'C# & .NET',
    question: '44. How do WebApplicationFactory<TEntryPoint> and Testcontainers enable realistic integration testing against real Docker databases in .NET?',
    difficulty: 'Senior (6+ YOE)',
    tags: ['C#', 'Integration Testing', 'WebApplicationFactory', 'Testcontainers', 'Docker'],
    shortSummary: 'Explains in-memory test server, DI service replacement, Testcontainers SQL Server/Postgres, and database isolation.',
    detailedAnswer: {
      executiveSummary: '`WebApplicationFactory<Program>` boots the full ASP.NET Core application pipeline in memory for end-to-end HTTP integration testing without binding to physical network ports. Combined with `Testcontainers for .NET`, tests spin up real, ephemeral Docker containers (SQL Server, Redis, RabbitMQ) for each test run, executing tests against production-identical database engines instead of unreliable in-memory database mocks.',
      keyPoints: [
        'WebApplicationFactory: Boots full Program.cs pipeline, middleware, routing, and filters in-memory.',
        'Testcontainers: Spawns real containerized SQL Server/PostgreSQL instances during test suite initialization.',
        'Service Replacement: Override specific DI services using `builder.ConfigureTestServices(services => ...)`.',
        'Database Isolation: Respawn database state between tests using `Respawn` or unique schema isolation.'
      ],
      codeOrQuerySnippet: {
        title: 'Integration Test with WebApplicationFactory and Testcontainers',
        language: 'csharp',
        code: `public class MortgageApiIntegrationTests : IAsyncLifetime
{
    private readonly MsSqlContainer _sqlContainer = new MsSqlBuilder()
        .WithImage("mcr.microsoft.com/mssql/server:2022-latest")
        .Build();

    private WebApplicationFactory<Program> _factory = null!;
    private HttpClient _client = null!;

    public async Task InitializeAsync()
    {
        await _sqlContainer.StartAsync();

        _factory = new WebApplicationFactory<Program>().WithWebHostBuilder(builder =>
        {
            builder.ConfigureTestServices(services =>
            {
                // Replace production connection with Testcontainer instance
                services.RemoveAll<DbContextOptions<MortgageDbContext>>();
                services.AddDbContext<MortgageDbContext>(options =>
                    options.UseSqlServer(_sqlContainer.GetConnectionString()));
            });
        });

        _client = _factory.CreateClient();
    }

    [Fact]
    public async Task CreateLoan_Returns201Created_AndPersistsToDatabase()
    {
        var payload = new CreateLoanDto("John Smith", 350000m);
        var response = await _client.PostAsJsonAsync("/api/v1/loans", payload);

        response.StatusCode.Should().Be(HttpStatusCode.Created);
    }

    public async Task DisposeAsync() => await _sqlContainer.DisposeAsync();
}`
      },
      proTipOrPitfall: 'Never use EF Core In-Memory database (`UseInMemoryDatabase`) for relational integration tests. It does not enforce foreign keys, relational constraints, or SQL transactions, producing false-positive test results.',
      studyResources: [
        {
          title: 'Integration tests in ASP.NET Core',
          url: 'https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests',
          source: 'Microsoft Learn'
        }
      ]
    }
  },
  {
    id: 'csnet-45',
    category: 'C# & .NET',
    question: '45. How does BenchmarkDotNet diagnose micro-optimizations, allocations, and JIT assemblies in .NET performance tuning?',
    difficulty: 'Staff / Lead Architect',
    tags: ['C#', 'BenchmarkDotNet', 'Performance', 'Memory Diagnoser', 'JIT Disassembly'],
    shortSummary: 'Covers warmups, statistical validation, MemoryDiagnoser allocation tracking, and DisassemblyDiagnoser.',
    detailedAnswer: {
      executiveSummary: '`BenchmarkDotNet` is the standard benchmarking library for .NET. It isolates benchmarks into dedicated out-of-process runs, executes statistical warmup cycles, prevents JIT dead-code stripping, and produces accurate nanosecond-level timings. The `[MemoryDiagnoser]` attribute measures allocated managed heap bytes and Gen 0/1/2 GC collections per operation.',
      keyPoints: [
        'Warmup & Statistical Rigor: Automatically detects and executes required warmup iterations until variance stabilizes.',
        'MemoryDiagnoser: Tracks exact bytes allocated on the heap and GC collections triggered.',
        'DisassemblyDiagnoser: Emits JIT-compiled x64 / ARM64 assembly instructions to verify SIMD vectorization and devirtualization.',
        'Dead-Code Prevention: Always return results or consume them with `Consumer` to prevent JIT from optimizing out test code.'
      ],
      codeOrQuerySnippet: {
        title: 'BenchmarkDotNet Suite with MemoryDiagnoser',
        language: 'csharp',
        code: `[MemoryDiagnoser]
[Orderer(SummaryOrderPolicy.FastestToSlowest)]
[RankColumn]
public class StringParsingBenchmark
{
    private const string RawData = "Account:98234710:Routing:121000358:Branch:Main";

    [Benchmark(Baseline = true)]
    public (string, string) ParseUsingStringSplit()
    {
        var parts = RawData.Split(':');
        return (parts[1], parts[3]); // Incurs multiple string[] and string heap allocations
    }

    [Benchmark]
    public (int, int) ParseUsingSpanZeroAllocation()
    {
        ReadOnlySpan<char> span = RawData.AsSpan();
        // Zero-allocation Span slicing and parsing
        int account = int.Parse(span.Slice(8, 8));
        int routing = int.Parse(span.Slice(25, 9));
        return (account, routing);
    }
}`
      },
      proTipOrPitfall: 'Always run benchmarks in `Release` configuration (`dotnet run -c Release`) without an attached debugger. Benchmarking `Debug` builds produces misleading figures that include unoptimized JIT code.',
      studyResources: [
        {
          title: 'BenchmarkDotNet Documentation',
          url: 'https://benchmarkdotnet.org/',
          source: 'BenchmarkDotNet'
        }
      ]
    }
  }
];
